### ISSUE TITLE
官网-快速接入-注册并且创建应用 放的链接有点问题

### ISSUE THREAD

**Issue by 2017jw** [wxpusher/wxpusher-docs#1]
官网-快速接入-注册并且创建应用 放的链接是http://wxpusher.zjiecode.com，这篇文档里面是http://wxpusher.zjiecode.com/admin，应该是这个文档里面的才对吧。

**Comment by zjiecode** [comment]
你真细心，是的，感谢🙏。

**Comment by zjiecode** [comment]
已经修复这个问题。
