### ISSUE TITLE
推送好像不是很稳定，有时候收不到

### ISSUE THREAD

**Issue by fanpenghuix** [wxpusher/wxpusher-docs#6]
我查了一下后台，然后再历史消息里面看了下，是有的，但是微信没有推送出来。

**Comment by zjiecode** [comment]
这个是已知的问题，目前在升级，发送量也有点大，达到微信的上线了。
目前已经基本上解决，如果有问题欢迎继续反馈。

**Comment by fanpenghuix** [comment]
> 目前已经基本上解决，如果有问题欢迎继续反馈。

这两天观察已经正常了。
